# This is name of the workflow that will be display in Actions Tab
name: CICD

# Manual click Device WorkFlow Whenever User Need

on:
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from GitHub"
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container Build"
        
  test:
     runs-on: ubuntu-latest
     steps:
      - name: Test the container
        run: echo "Testing the Container"
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
    
