name: Secret Env Demo

on:
    push:
    
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Use Secret as Environment Variable
              env:
                MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                echo "Secret is configured"
                if [ -n "$MY_SECRET" ]; then
                  echo "The secret is set: true"
                fi